### ISSUE TITLE
What is the exact difference between cdktf synth and this?

### ISSUE THREAD

**Issue by shinebayar-g** [cdktf/cdktf-tf-module-stack#294]
### Description

Documentation at https://developer.hashicorp.com/terraform/cdktf/concepts/hcl-interoperability mentions just run cdktf synth, copy the `cdktf.out/stacks/<stack-name>/cdktf.json`. This works.

It's unclear why this repository exists and what is the difference between `cdktf synth` json output and this.

Could you explain the use case?

### Links

https://developer.hashicorp.com/terraform/cdktf/concepts/hcl-interoperability
https://developer.hashicorp.com/terraform/cdktf/develop-custom-constructs/publishing-and-distribution

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
Sure, the normal TerraformStack has a mandatory backend being applied, the providers are pinned to specific versions, etc. This makes it harder to create a shareable module out of the generated code.
